# robotpkg motion generation software
#

COMMENT=	Motion generation software

SUBDIR+=	contlaw
SUBDIR+=	libmwalk
SUBDIR+=	locoDemo-genom
SUBDIR+=	mwalk-genom
SUBDIR+=	pilo-genom
SUBDIR+=	softMotion-libs

include ../mk/robotpkg.subdir.mk
