# robotpkg Makefile for:	devel/gbx-flexiport
# Created:			Anthony Mallet on Wed, 17 Mar 2010
#
GBX_PACKAGE=	flexiport-1.0.0
GBX_COMMENT=	Flexiport (interface for a range of data port types)

CATEGORIES=	devel
include ../../meta-pkgs/gearbox/Makefile.common

CMAKE_ARGS+=	-DENABLE_LIB_FLEXIPORT=ON

include ../../devel/gbx-share/depend.mk
include ../../mk/robotpkg.mk
