# robotpkg map building software
#

COMMENT=	Map building software

SUBDIR+=	dtm-genom
SUBDIR+=	libdtm
SUBDIR+=	mapkit
SUBDIR+=	segkit
SUBDIR+=	worldmodelgrid3d
SUBDIR+=	worldmodelgrid3dg-genom
SUBDIR+=	zone-genom

include ../mk/robotpkg.subdir.mk
