# robotpkg path planning algorithms
#
# Please list in alphabetical order
#

COMMENT=	Path planning algorithms and tools

SUBDIR+=	aspect-genom
SUBDIR+=	gik-genom
SUBDIR+=	hpp-core
SUBDIR+=	hpp-dynamic-obstacle
SUBDIR+=	hpp-gik
SUBDIR+=	hpp-hik
SUBDIR+=	hpp-localstepper
SUBDIR+=	hpp-openhrp
SUBDIR+=	hpp-walkfootplanner
SUBDIR+=	hpp-walkplanner
SUBDIR+=	hpp-worldmodelplanner
SUBDIR+=	jrl-walkgen
SUBDIR+=	kineo-pp
SUBDIR+=	libp3d
SUBDIR+=	ndd-genom
SUBDIR+=	p3d-genom
SUBDIR+=	walk-genom
SUBDIR+=	worldModelPlanner-genom

include ../mk/robotpkg.subdir.mk
