# robotpkg Makefile for:	devel/mkdep
# Created:			Anthony Mallet on Sun, 28 Jan 2007
#

DISTNAME=		mkdep-2.7
CATEGORIES=		devel
MASTER_SITES=		${MASTER_SITE_OPENROBOTS}

MAINTAINER=		openrobots@laas.fr
HOMEPAGE=		https://softs.laas.fr/openrobots/wiki/mkdep
COMMENT=		Automated make(1) dependency generation

LICENSE=		2-clause-bsd

NOT_FOR_PLATFORM=	# empty
GNU_CONFIGURE=		yes

include ../../mk/robotpkg.mk
