# robotpkg Makefile for:	localization/libpom
# Created:			Anthony Mallet on Tue, 20 Nov 2007
#

DISTNAME=		libpom-1.2
CATEGORIES=		localization
MASTER_SITES=		${MASTER_SITE_OPENROBOTS:=libpom/}

MAINTAINER=		openrobots@laas.fr
COMMENT=		Global robot position management library.
LICENSE=		2-clause-bsd

NOT_FOR_PLATFORM=	# empty
GNU_CONFIGURE=		yes

include ../../math/t3d/depend.mk
include ../../pkgtools/libtool/depend.mk
include ../../pkgtools/pkg-config/depend.mk
include ../../mk/robotpkg.mk
