# robotpkg Makefile for:	audio/clone-genom
# Created:			Matthieu Herrb on Wed, 21 Jan 2009
#

DISTNAME=	clone-genom-0.1
CATEGORIES=	audio
MASTER_SITES=	${MASTER_SITE_OPENROBOTS:=clone-genom/}
MASTER_REPOSITORY=	${MASTER_REPOSITORY_OPENROBOTS}clone-genom

MAINTAINER=	openrobots@laas.fr
COMMENT=	3D Animated speaking head - genom component

GNU_CONFIGURE=	yes

GENOM_MODULE=	clone

include ../../architecture/genom/depend.mk
include ../../localization/pom-genom/depend.mk
include ../../architecture/genBasic-genom/depend.mk
include ../../mk/robotpkg.mk
