#!/bin/sh
#
# Copyright (c) 2006,2008-2010 LAAS/CNRS
# Copyright (c) 2001-2002 Alistair G. Crooks.
# All rights reserved.
#
# This project includes software developed by the NetBSD Foundation, Inc.
# and its contributors. It is derived from the 'pkgsrc' project
# (http://www.pkgsrc.org).
#
# Redistribution  and  use in source   and binary forms,  with or without
# modification, are permitted provided that  the following conditions are
# met:
#
#   1. Redistributions  of  source code must  retain  the above copyright
#      notice, this list of conditions and the following disclaimer.
#   2. Redistributions in binary form must  reproduce the above copyright
#      notice,  this list of  conditions and  the following disclaimer in
#      the  documentation   and/or  other  materials   provided with  the
#      distribution.
#   3. All advertising materials mentioning   features or use of this
#      software must display the following acknowledgement:
#	This product includes software developed by Alistair G. Crooks
#	for the NetBSD project.
#   4. Neither the  name  of The NetBSD Foundation  nor the names  of its
#      contributors  may be  used to endorse or promote  products derived
#      from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHORS AND CONTRIBUTORS ``AS IS'' AND
# ANY  EXPRESS OR IMPLIED WARRANTIES, INCLUDING,  BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES   OF MERCHANTABILITY AND  FITNESS  FOR  A PARTICULAR
# PURPOSE ARE DISCLAIMED.  IN NO  EVENT SHALL THE AUTHOR OR  CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT,  INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING,  BUT  NOT LIMITED TO, PROCUREMENT  OF
# SUBSTITUTE  GOODS OR SERVICES;  LOSS   OF  USE,  DATA, OR PROFITS;   OR
# BUSINESS  INTERRUPTION) HOWEVER CAUSED AND  ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE  USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# From $NetBSD: bootstrap,v 1.88 2006/11/06 21:08:42 tv Exp $
#
#                                       Anthony Mallet on Sun Oct  1 2006
#

# where the building takes place
bootstrapdir=`dirname "$0"`
bootstrapdir=`cd "${bootstrapdir}" && pwd`
pkgsrcdir=`dirname "${bootstrapdir}"`
wrkdir="`pwd`/work"

usage="Usage: $0 "'
    [ --workdir <workdir> ]
    [ --prefix <prefix> ]
    [ --pkgdbdir <pkgdbdir> ]
    [ --pkgmandir <pkgmandir> ]
    [ --sysconfdir <sysconfdir> ]
    [ --fetch-cmd <ftp command> ]
    [ --compiler <compiler> ]
    [ --make <make command> ]
    [ --syslibsuffix <libsuffix> ]
    [ --help ]'

opsys=`uname -s | tr -d /`

die()
{
	echo >&2 "$@"
	exit 1
}

echo_msg()
{
    echo "===> $@"
}

check_prog()
{
    _var="$1"; _name="$2"

    eval _tmp=\"\$$_var\"
    if [ "x$_tmp" != "x" ]; then
	# Variable is already set (by the user, for example)
	return 0
    fi

    for _d in `echo $PATH | tr ':' ' '`; do
	if [ -x "$_d/$_name" ]; then
	    # Program found
	    eval $_var=\""$_d/$_name"\"
	    return 1
	fi
    done

    die "$_name not found in path."
}

# run a command, abort if it fails
run_cmd()
{
    echo_msg "running: $@"
    eval "$@"
    ret=$?
    if [ $ret -ne 0 ]; then
	echo_msg "exited with status $ret"
	die "aborted."
    fi
}

# run a command verbosely
echo_cmd()
{
    echo "running: $@"
    eval "$@"
}

mkdir_p()
{
    run_cmd "mkdir -p $@"
}

copy_src()
{
    _src="$1"; _dst="$2"
    if [ ! -d $wrkdir/$_dst ]; then
	mkdir_p $wrkdir/$_dst
    fi
    $cpprog -r $_src/* $wrkdir/$_dst
}

get_optarg()
{
    expr "x$1" : "x[^=]*=\\(.*\\)"
}

# user configurable options
prefix=
pkgdbdir=
mandir=
sysconfdir=
compiler=""
gmake=make
syslibsuffix=

while [ $# -gt 0 ]; do
	case $1 in
	--workdir=*)		wrkdir=`get_optarg "$1"` ;;
	--workdir)		wrkdir="$2"; shift ;;
	--prefix=*)		prefix=`get_optarg "$1"` ;;
	--prefix)		prefix="$2"; shift ;;
	--pkgdbdir=*)		pkgdbdir=`get_optarg "$1"` ;;
	--pkgdbdir)		pkgdbdir="$2"; shift ;;
	--mandir=*)		mandir=`get_optarg "$1"` ;;
	--mandir)		mandir="$2"; shift ;;
	--sysconfdir=*)		sysconfdir=`get_optarg "$1"` ;;
	--sysconfdir)		sysconfdir="$2"; shift ;;
	--fetch-cmd=*)		fetch_cmd=`get_optarg "$1"` ;;
	--fetch-cmd)		fetch_cmd="$a"; shift ;;
	--compiler=*)		compiler=`get_optarg "$1"` ;;
	--compiler)		compiler="$2"; shift ;;
	--make=*)		gmake=`get_optarg "$1"` ;;
	--make)			gmake="$2"; shift ;;
	--syslibsuffix=*)	syslibsuffix=`get_optarg "$1"` ;;
	--syslibsuffix)		syslibsuffix="$2"; shift ;;
	--help)			echo "$usage"; exit ;;
	-h)			echo "$usage"; exit ;;
	--*)			echo "$usage"; exit 1 ;;
	esac
	shift
done

# set defaults for system locations if not already set by the user
[ -z "$prefix" ] && prefix=/opt/openrobots
[ -z "$pkgdbdir" ] && pkgdbdir=${prefix}/var/db/robotpkg
[ -z "$mandir" ] && mandir=${prefix}/man
[ -z "$sysconfdir" ] && sysconfdir=${prefix}/etc

case "$opsys" in
Darwin)
	machine_arch=`uname -p`
	;;
Linux)
	machine_arch=`uname -m | sed -e 's/i.86/i386/' -e 's/ppc/powerpc/'`
	;;
NetBSD)
	gmake=gmake
	;;
SunOS)
	gmake=gmake
	;;
esac

# export OPSYS and MACHINE_ARCH for pkg_install. we only set
# MACHINE_ARCH on platforms where we override bmake's value.
OPSYS=${opsys}
export OPSYS
if [ "${machine_arch}" != "" ]; then
	MACHINE_ARCH=${machine_arch}
	export MACHINE_ARCH
fi

if [ -n "$CP" ]; then
    cpprog="$CP"
else
    check_prog cpprog cp
fi


# --- preserve existing settings -------------------------------------------

test -f ${sysconfdir}/robotpkg.conf && {
  echo "===================================================================="
  echo "An existing installation has been detected in"
  echo "${sysconfdir}/robotpkg.conf"
  echo
  echo "If you really want to bootstrap to this location, move away this file"
  echo "first. After bootstrap, you will have to manually merge your previous"
  echo "settings into the new robotpkg.conf file created during bootstrap."
  echo "===================================================================="
  die '***' Fatal Error
}

build_start=`date`
echo_msg "bootstrap command: $0 $@"
echo_msg "bootstrap started: $build_start"


# --- create the initial prefix directory ----------------------------

[ -x "$prefix" ] || {
  echo_msg "Creating ${prefix} directory"
  echo_cmd mkdir -p "$prefix" ||
    die "Please create a directory ${prefix}, writable by you.
You can also do $0 --prefix <path> to bootstrap with <path> prefix."

  echo_cmd chmod u+rwx "${prefix}" ||
    die "Could not make ${prefix} writable by you. Please do it manually."
}

[ -r "$prefix" -a -w "$prefix" ] ||
  die "Please make ${prefix} readable and writable by you."


# --- set up an example mk.conf file ---------------------------------

export MKCONF_EXAMPLE=${wrkdir}/robotpkg.conf.example

echo_msg "Creating robotpkg.conf.example in ${wrkdir}"
mkdir_p ${wrkdir}
>${MKCONF_EXAMPLE}

echo "# Example robotpkg.conf settings produced by robotpkg/bootstrap" \
    >> ${MKCONF_EXAMPLE}
echo "# `date`" >> ${MKCONF_EXAMPLE}
echo >> ${MKCONF_EXAMPLE}

if [ "$compiler" != "" ]; then
	echo "ROBOTPKG_COMPILER=	$compiler" >> ${MKCONF_EXAMPLE}
fi

# save environment in example mk.conf
echo "LOCALBASE=		$prefix" >> ${MKCONF_EXAMPLE}
if [ "${pkgdbdir}" != "${prefix}/var/db/robotpkg" ]; then
    echo "PKG_DBDIR=		$pkgdbdir" >> ${MKCONF_EXAMPLE}
fi
if [ "${sysconfdir}" != "${prefix}/etc" ]; then
    echo "PKG_SYSCONFBASE=	$sysconfdir" >> ${MKCONF_EXAMPLE}
fi
echo "" >> ${MKCONF_EXAMPLE}
if [ "${syslibsuffix}" != "" ]; then
	echo "SYSLIBSUFFIX=	$syslibsuffix" >> ${MKCONF_EXAMPLE}
fi
echo "" >> ${MKCONF_EXAMPLE}

# create installation directories
mkdir_p $prefix $pkgdbdir $prefix/sbin
mkdir_p $mandir/man1 $mandir/cat1
mkdir_p $mandir/man8 $mandir/cat8


# --- build libnbcompat ----------------------------------------------

echo_msg "Building libnbcompat"
copy_src $pkgsrcdir/pkgtools/libnbcompat/dist libnbcompat
run_cmd "(						\
    cd $wrkdir/libnbcompat;				\
    $shprog ./configure -C $configure_quiet_flags	\
	--prefix=$prefix --sysconfdir=$sysconfdir	\
	--enable-bsd-getopt --enable-db			\
    && $gmake						\
)"


# --- bootstrap pkg_install ------------------------------------------

# This will install a minimal version of the robotpkg_admin tools.
# Then the regular robotpkg framework will be functional and the regular
# robotpkg_admin tools will be pulled up as a build dependency of every
# package.
echo_msg "Installing package administrative tools"
copy_src $pkgsrcdir/pkgtools/pkg_install/dist pkg_install
run_cmd "(							\
    cd $wrkdir/pkg_install;					\
    env $BSTRAP_ENV						\
    CPPFLAGS='$CPPFLAGS -I../libnbcompat -I../../libnbcompat'	\
    LDFLAGS='$LDFLAGS -L../libnbcompat -L../../libnbcompat'	\
    LIBS='-lnbcompat'						\
    $shprog ./configure -C $configure_quiet_flags		\
	--enable-bootstrap					\
	--prefix=$prefix --sysconfdir=$sysconfdir		\
	--with-pkgdbdir=$pkgdbdir --mandir=$mandir		\
	$pkg_install_args					\
    && $gmake && $gmake install					\
)"

# Aggressively remove any previous pkg_install entries in pkgdb.
#
oldpkg=`$prefix/sbin/robotpkg_admin -b -d $pkgdbdir -S lsall pkg_install ||:`
test -z "$oldpkg" || echo_msg "Removing exisiting pkg_install entries"
for p in $oldpkg; do
    run_cmd "$prefix/sbin/robotpkg_admin delete $p"
    test -d $pkgdbdir/$p && run_cmd "rm -rf $pkgdbdir/$p"
done

# Register the installed package, with version = 0 so that the regular
# package will be fetched automatically when installing other software.
echo_msg "Registering installed package"
run_cmd "(							\
    cd $pkgsrcdir/pkgtools/pkg_install &&			\
    $gmake MAKECONF=${MKCONF_EXAMPLE} VERSION=0	NO_DEPENDS=yes	\
	WRKSRC=$wrkdir/pkg_install PLIST_SRC=PLIST.bootstrap	\
	bootstrap-register					\
)"


# preserve compiler and tool environment variables settings
test -z "$CP" || echo "TOOLS_PLATFORM.cp?=		$CP" >> ${MKCONF_EXAMPLE}
test -z "$GREP" || echo "TOOLS_PLATFORM.grep?=		$GREP" >> ${MKCONF_EXAMPLE}
test -z "$ID" || echo "TOOLS_PLATFORM.id?=		$ID" >> ${MKCONF_EXAMPLE}
test -z "$MKDIR" || echo "TOOLS_PLATFORM.mkdir?=		$MKDIR" >> ${MKCONF_EXAMPLE}
test -z "$TEST" || echo "TOOLS_PLATFORM.test?=		$TEST" >> ${MKCONF_EXAMPLE}
test -z "$TOUCH" || echo "TOOLS_PLATFORM.touch?=		$TOUCH" >> ${MKCONF_EXAMPLE}
test -z "$XARGS" || echo "TOOLS_PLATFORM.xargs?=		$XARGS" >> ${MKCONF_EXAMPLE}
test -z "$CFLAGS" || (
	echo "CFLAGS+=		$CFLAGS" >> ${MKCONF_EXAMPLE}
	echo "DBG=			# prevent DBG from adding default optimizer flags" >> ${MKCONF_EXAMPLE}
)
test -z "$CPPFLAGS" || echo "CPPFLAGS+=		$CPPFLAGS" >> ${MKCONF_EXAMPLE}
test -z "$LDFLAGS" || echo "LDFLAGS+=		$LDFLAGS" >> ${MKCONF_EXAMPLE}

echo "" >> ${MKCONF_EXAMPLE}


# Install sample config file
sysconffile=${sysconfdir}/robotpkg.conf
mkdir_p ${sysconfdir}
run_cmd $cpprog ${MKCONF_EXAMPLE} ${sysconffile}


# --- cleanup --------------------------------------------------------

run_cmd ${bootstrapdir}/cleanup

hline="==========================================================================="
echo ""
echo "$hline"
echo ""
echo "Hopefully everything is now complete."
echo ""
echo "An example robotpkg.conf file with the settings you provided to \"bootstrap\""
echo "has been created for you. It can be found in:"
echo ""
echo "      ${sysconffile}"
echo ""
echo "You can start building packages by changing to some package directory"
echo "and then doing \"${gmake} update\" in that directory."
#echo
#echo "You can find extensive documentation of the robotics packages collection"
#echo "in $pkgsrcdir/doc/robotpkg.txt."
echo ""
if test "$prefix" != "/opt/openrobots"; then
  echo "==> Please either add $prefix/sbin to your PATH variable"
  echo "or, alternatively, set the ROBOTPKG_BASE variable to $prefix"
  echo "in your environment. Otherwise robotpkg won't work."
  echo ""
fi
echo "Thank you."
echo ""
echo "$hline"
echo ""

echo_msg "bootstrap started: $build_start"
echo_msg "bootstrap ended:   `date`"

exit 0
