# robotpkg Makefile for:	sysutils/alog
# Created:			Matthieu Herrb on Mon, 12 Jan 2009
#

DISTNAME=	alog-0.4
PKGREVISION=	1
COMMENT=	a simple log data viewing tool

CATEGORIES=	sysutils

MASTER_SITES=	${MASTER_SITE_OPENROBOTS:=alog/}

MAINTAINER=	openrobots@laas.fr

GNU_CONFIGURE=	yes

include ../../mk/sysdep/tcl.mk
include ../../mk/sysdep/tk.mk
include ../../mk/sysdep/bwidget.mk
include ../../mk/robotpkg.mk
