# robotpkg Makefile for:	architecture/genHum-genom
# Created:			Matthieu Herrb on Tue, 24 Mar 2009
#

DISTNAME=		genHum-genom-0.1
CATEGORIES=		architecture

MASTER_SITES=		${MASTER_SITE_OPENROBOTS}
MASTER_REPOSITORY=	git ssh://trac.laas.fr/git/robots/genHum-genom

MAINTAINER=		openrobots@laas.fr
#HOMEPAGE=
COMMENT=		Common data structures for human models

GNU_CONFIGURE=		yes

GENOM_MODULE=		genHum
GENOM_ARGS=		-a

include ../../architecture/genom/depend.mk

include ../../mk/robotpkg.mk
