# robotpkg Makefile for:	audio/sphinx2
# Created:			Anthony Mallet on Mon, 14 Apr 2008
#

DISTNAME=		sphinx2-0.6
CATEGORIES=		audio
MASTER_SITES=		${MASTER_SITE_SOURCEFORGE:=cmusphinx/}

MAINTAINER=		openrobots@laas.fr
HOMEPAGE=		http://cmusphinx.sourceforge.net
COMMENT=		Carnegie Mellon University\'s speech recognition engine.
LICENSE=		2-clause-bsd

GNU_CONFIGURE=		yes

include ../../pkgtools/libtool/depend.mk
include ../../mk/robotpkg.mk
