# robotpkg Makefile for:	motion/contlaw
# Created:			Matthieu Herrb on Tue, 30 Dec 2008
#

DISTNAME=	contlaw-1.0
CATEGORIES=	motion
MASTER_SITE=	${MASTER_SITE_OPENROBOTS}
MASTER_REPOSITORY=	git ssh://trac.laas.fr/git/robots/contlaw

MAINTAINER=	openrobots@laas.fr
COMMENT=	Control laws for wheeled robots with optional trailers

GNU_CONFIGURE=	yes

include ../../architecture/genPos-genom/depend.mk
include ../../devel/mkdep/depend.mk
include ../../pkgtools/pkg-config/depend.mk
include ../../mk/robotpkg.mk

