# robotpkg Makefile for:	lang/sun-jre14
# Created:			Anthony Mallet on Fri, 5 Jan 2007
#

DISTNAME=	j2re-1_4_2_13-linux-i586
PKGNAME=	sun-jre14-2.13
MASTER_SITES=	# empty

SHORT=		JRE
COMMENT=	Sun's Java(tm) 2 Runtime Environment 1.4.2 #'

WRKSRC=		${WRKDIR}/j2re1.4.2_13
JAVA_WRAPPERS=	java keytool orbd policytool rmid rmiregistry \
		servertool tnameserv

include ../../lang/sun-jre14/Makefile.common
