#!/bin/sh
#
# Copyright (c) 2006 LAAS/CNRS                        --  Thu Dec  7 2006
# All rights reserved.
#
# Redistribution  and  use in source   and binary forms,  with or without
# modification, are permitted provided that  the following conditions are
# met:
#
#   1. Redistributions  of  source code must  retain  the above copyright
#      notice, this list of conditions and the following disclaimer.
#   2. Redistributions in binary form must  reproduce the above copyright
#      notice,  this list of  conditions and  the following disclaimer in
#      the  documentation   and/or  other  materials   provided with  the
#      distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHORS AND CONTRIBUTORS ``AS IS'' AND
# ANY  EXPRESS OR IMPLIED WARRANTIES, INCLUDING,  BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES   OF MERCHANTABILITY AND  FITNESS  FOR  A PARTICULAR
# PURPOSE ARE DISCLAIMED.  IN NO  EVENT SHALL THE AUTHOR OR  CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT,  INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING,  BUT  NOT LIMITED TO, PROCUREMENT  OF
# SUBSTITUTE  GOODS OR SERVICES;  LOSS   OF  USE,  DATA, OR PROFITS;   OR
# BUSINESS  INTERRUPTION) HOWEVER CAUSED AND  ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE  USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

# compute sed command
prefix=robot
subst=
for s in add admin create delete info view summary audit-packages; do
    subst="$subst -e 's|${prefix}pkg_$s|pkg_$s|g'"
    subst="$subst -e 's|pkg_$s|${prefix}pkg_$s|g'"
done
subst="$subst -e 's|pkgsrc|robotpkg|g'"

# replace files
find . -type f | while read f; do
 tmp=$f.subst.sav
 mv "$f" "$tmp" || exit 1
 eval sed $subst < "$tmp" > "$f"
 if test -x "$tmp"; then
    chmod +x "$f"
 fi
 if cmp -s "$tmp" "$f"; then
   mv -f "$tmp" "$f";
 else
   rm -f "$tmp"
   echo subst $f
 fi
 n=`echo $f | eval sed $subst`
 if test "$n" != "$f"; then
   mv $f $n
   echo renamed $n
 fi
done
