# robotpkg Makefile for:	mapping/zone-genom
# Created:			Matthieu Herrb on Mon, 9 Mar 2009
#

COMMENT=	GenoM module managing zones in a map
DISTNAME=	zone-genom-1.1
CATEGORIES=	mapping
MASTER_SITES=	${MASTER_SITE_OPENROBOTS:=zone/}
MASTER_REPOSITORY=	git ssh://trac.laas.fr/git/robots/zone-genom

MAINTAINER=	openrobots@laas.fr

GNU_CONFIGURE=	yes
GENOM_MODULE=	zone

include ../../architecture/genom/depend.mk
include ../../architecture/genBasic-genom/depend.mk
include ../../hardware/sick-genom/depend.mk
include ../../localization/segloc-genom/depend.mk
include ../../path/aspect-genom/depend.mk
include ../../mk/robotpkg.mk
