# robotpkg Makefile for:	devel/jrl-modelloader
# Created:			Anthony Mallet on Tue, 12 Jun 2007
#

DISTNAME=		jrl-modelloader-1.4
CATEGORIES=		devel
MASTER_SITES=		${MASTER_SITE_JRL}

RESTRICTED=		You cannot redistribute this software.
NO_PUBLIC_SRC=		${RESTRICTED}
NO_PUBLIC_BIN=		${RESTRICTED}

MAINTAINER=		hpp@laas.fr
COMMENT=		CORBA server for VRML model loader.

GNU_CONFIGURE=		yes
NO_BUILD=		yes

include ../../mk/robotpkg.mk
