# robotpkg Makefile for:	hardware/mouse3d-genom
# Created:			Xavier Broquere on Fri, 20 Mar 2009
#

DISTNAME=		mouse3d-genom-1.0
CATEGORIES=		hardware	
MASTER_SITES=		${MASTER_SITE_OPENROBOTS}

MAINTAINER=		openrobots@laas.fr
#HOMEPAGE=
COMMENT=		

GNU_CONFIGURE=		yes

GENOM_MODULE=		mouse3d
include ../../architecture/genom/depend.mk

include ../../hardware/spnav-kmod/depend.mk
include ../../hardware/spnav-libs/depend.mk
include ../../mk/robotpkg.mk
