#!/bin/sh
# $NetBSD: pre-build,v 1.66 2007/01/28 19:23:22 kristerw Exp $
#
# Clean up system to be ready for bulk pkg build
#
# (c) 2000 Hubert Feyrer, All Rights Reserved.
#

#set -v		# Debug

# Pull in USR_ROBOTPKG:
if [ -f "$BULK_BUILD_CONF" ]; then
    . "$BULK_BUILD_CONF"
else
    . `dirname $0`/build.conf
fi

PRUNELINKS=${PRUNEPACKAGES:-"yes"}

PKGDIGEST_PKG_DIR=${USR_ROBOTPKG}/pkgtools/digest

# Extract the name of the files used for the build log and broken build log.
# These have defaults set by bsd.bulk-pkg.mk and may be overridden in
# /etc/mk.conf
BULKFILESDIR=`( cd ${PKGDIGEST_PKG_DIR} ; ${MAKE} show-var VARNAME=BULKFILESDIR )`;
if [ "$BULKFILESDIR" = "" ]; then
	echo "pre-build> Had problems determining the directory of .broken* files"
	exit 1
fi
BROKENF=`( cd ${PKGDIGEST_PKG_DIR} ; ${MAKE} show-var VARNAME=BROKENFILE )`;
if [ "$BROKENF" = "" ]; then
	echo "pre-build> Had problems determining the name of the .broken files"
	exit 1
fi
NOTAVAILF=`( cd ${PKGDIGEST_PKG_DIR} ; ${MAKE} show-var VARNAME=NOT_AVAILABLE_FILE )`;
if [ "$NOTAVAILF" = "" ]; then
	echo "pre-build> Had problems determining the name of the .bulk-not_available files"
	exit 1
fi
BRKWRKLOG=`( cd ${PKGDIGEST_PKG_DIR} ; ${MAKE} show-var VARNAME=BROKENWRKLOG )`;
if [ "$BRKWRKLOG" = "" ]; then
	echo "pre-build> Had problems determining the name of the .broken.work files"
	exit 1
fi
BLDLOG=`( cd ${PKGDIGEST_PKG_DIR} ; ${MAKE} show-var VARNAME=BUILDLOG )`;
if [ "$BLDLOG" = "" ]; then
	echo "pre-build> Had problems determining the name of the .make files"
	exit 1
fi
STARTFILE=`( cd ${PKGDIGEST_PKG_DIR} ; ${MAKE} show-var VARNAME=STARTFILE )`;
if [ "$STARTFILE" = "" ]; then
	echo "pre-build> Had problems determining the name of the .start file"
	exit 1
fi

LOCALBASE=`( cd ${PKGDIGEST_PKG_DIR} ; ${MAKE} show-var VARNAME=LOCALBASE )`;
DISTDIR=`( cd ${PKGDIGEST_PKG_DIR} ; ${MAKE} show-var VARNAME=DISTDIR )`;

# Create ${BULKFILESDIR} if necessary
echo "pre-build> Creating ${BULKFILESDIR} if necessary"
mkdir -p "${BULKFILESDIR}"


# Clean up state files
cd "${USR_ROBOTPKG}"
echo "pre-build> Cleaning up leftover state files from previous runs"
rm -f "${BULKFILESDIR}"/*/*/$BROKENF "${BULKFILESDIR}"/*/*/$BRKWRKLOG "${BULKFILESDIR}"/*/*/$BLDLOG
rm -f "${BULKFILESDIR}"/*/*/$NOTAVAILF
rm -f "${BULKFILESDIR}/$BROKENF" "${BULKFILESDIR}/$BRKWRKLOG" "${BULKFILESDIR}/$BLDLOG" "$STARTFILE"


#
# Remove old/broken distfiles and binary packages
#
case "$PRUNELINKS" in
yes|YES)
	echo "pre-build> Checking for and removing orphaned packages links"
	PACKAGES=`( cd "${PKGDIGEST_PKG_DIR}" && ${MAKE} show-var VARNAME=PACKAGES )`
	find "$PACKAGES" -type l -print |  \
	while read f
	do
		if [ ! -d "$f" -a ! -f "$f" ]; then
			echo "pre-build> Removing orphaned link: \"$f\""
			rm "$f"
		fi
	done
	echo "pre-build> done."
	;;
*)
	echo "pre-build> Skipping pruning of packages links."
	;;
esac

cd "${USR_ROBOTPKG}"
echo "This file marks the start time of the bulk build." > "$STARTFILE"
