#!/bin/sh
# $Id: upload 2007/06/14 16:28:08 mallet $

#
# Upload non-restricted binary pkgs to ftp server
#

AWK=${AWK:-/usr/bin/awk}

set -eu

#
# Find out where we are
#
scriptdir=`dirname "$0"`
scriptdir=`cd "${scriptdir}" && pwd`

usage()
{
cat << EOF

$prog:  Uploads binary packages.

Usage:  $prog [-n|--no-upload] [-d|--debug] [-v|--verbose]
	$prog -h|--help
        $prog -V|--version

    -c|--config <file>
			Load the following configuration file instead of the default
			one.
    -d|--debug          Preserves some intermediate files to help
			debug any problems.

    -h|--help           Displays this help message and exits.

    -n|--no-upload      Does all of the work except for the actual upload.
			This option may be used to generate the upload script
			along with the list of packages to be excluded.

    -i|--no-install	Do not install the required packages; assume instead
			that they are already available.

    -v|--verbose        Enables verbose output.

    -V|--version        Displays the version of this script and exits.

Example:

    cd /usr/openrobots/robotpkg && $prog

Environment Variables:

    AWK  --  If specified, sets the awk program to be used

Files:

    pkgsrc/mk/bulk/build.conf

EOF
}

prog=$0
debug=no
do_upload=yes
do_install=yes
verbose=no
while test $# -gt 0; do
	case "$1" in
	-c|--config)
		shift
		BULK_BUILD_CONF=$1; shift
		;;
	-d|--debug)
		debug=yes
		shift
		;;

	-h|--help)
		usage
		exit 0
		;;

	-i|--no-install)
		do_install=no
		shift
		;;

	-n|--no-upload)
		do_upload=no
		shift
		;;

	-v|--verbose)
		verbose=yes
		shift
		;;

	-V|--version)
		${AWK} '/^#[ \t]*\$NetBSD/ {gsub(/,v/,"",$3);printf("%s:  Version %s, %s\n",$3,$4,$5); exit 0;}' $prog
		exit 0
		;;

	-*)
		echo "$prog:  Unknown option:  $1" 1>&2
		usage
		exit 1
		;;

	*)
		break
		;;
	esac
done
if test "$#" -gt 0; then
	echo "$prog:  Unknown argument: $1" 1>&2
	usage
	exit 1
fi

install_required()
{

	[ "$do_install" = "yes" ] || return 0
	pkg=$1
	if [ "${verbose}" = "yes" ]; then
		echo "upload> Installing ${pkg}"
	fi
	(cd "$USR_ROBOTPKG" && cd "$pkg" && ${MAKE} bulk-install) \
	|| {
		echo "upload> ERROR: Unable to install required package $pkg!" 1>&2
		echo "        Bailing out -- you're on your own." 1>&2
		exit 1
	}
}

#
# Get the variables MAKECONF, RSYNC_DST, RSYNC_OPTS from the bulk build
# configuration file.
#
: ${BULK_BUILD_CONF:="${scriptdir}/build.conf"} #"
. "${BULK_BUILD_CONF}"
. "${scriptdir}/post-build-conf"
check_config_vars
export_config_vars

cd $USR_ROBOTPKG

if [ -z "$RSYNC_DST" ]; then
	echo "upload> ERROR: You must set the variable RSYNC_DST, see build.conf-example." 1>&2
	exit 1
fi

MD5="$LOCALBASE/bin/digest md5";
SHA1="$LOCALBASE/bin/digest sha1";

REQUIRED_PACKAGES="pkgtools/digest"

opsys=`uname -s`
case "$opsys" in
NetBSD)	MAKE=gmake;
	SYSVSUM="sum -o 2";
	;;
*)	MAKE=make ;;
esac

export MAKE

# Bring in variables for bulk-install
BATCH=1
DEPENDS_TARGET=bulk-install
export BATCH DEPENDS_TARGET

#
# Some temp files
#

umask 022
TMPDIR="${TMPDIR:-/tmp}"
TMP="${TMPDIR}"/pkg_upload.$$
(umask 077 && mkdir "${TMP}") \
|| {
        echo "upload> ERROR: cannot create temporary directory \"${TMP}\"." 1>&2
        exit 1
}

restricted_packages="$TMP/restricted_packages"
good_packages="$TMP/regular_packages"
all_good_packages="$TMP/all_regular_packages"

upload_general="$TMP"/upload_general

# May be different than $USR_ROBOTPKG:
echo "upload> Running ${MAKE} to get the pkgsrc variables"
pkgsrcdir=`cd pkgtools/digest ; ${MAKE} show-var VARNAME=_ROBOTPKG_DIR`
packages=`cd pkgtools/digest ; ${MAKE} show-var VARNAME=PACKAGES`
distdir=`cd pkgtools/digest ; ${MAKE} show-var VARNAME=DISTDIR`
gzip_cmd=`cd pkgtools/digest; ${MAKE} show-var VARNAME=GZIP_CMD USE_TOOLS=gzip`
pkg_info=`cd pkgtools/digest && ${MAKE} show-var VARNAME=PKG_INFO`

# Pull in some pkgs needed
for pkg in ${REQUIRED_PACKAGES}; do
	install_required $pkg
done

RSFLAGS="-vap --progress $RSYNC_OPTS"

failed=no
cd $packages

echo "upload> Checking for restricted packages"
(cd All && env PKG_INFO="${pkg_info}" OUTDIR="${TMP}" sh "${pkgsrcdir}/mk/bulk/sort-packages")

# Add the name of the package file, including all its symlinks to the
# list of files to be uploaded.
while read package; do
	ls -1 */"$package"
done < "$good_packages" > "$all_good_packages"

if [ "${MKSUMS}" = "yes" -o "${MKSUMS}" = "YES" ]; then

	echo "upload> Calculating checksum files..."

	SUMFILES="MD5 SHA1"

	rm -f ${SUMFILES}

	install_required "pkgtools/digest"
	for pkg in `cat "${good_packages}"`; do
		pkg="All/$pkg"
		${MD5}		"$pkg" >> MD5
		${SHA1}		"$pkg" >> SHA1
	done
fi

if [ "${MKSUMMARY-}" = "yes" -o "${MKSUMMARY-}" = "YES" ]; then
	echo "upload> Creating summary file..."
	(cd "${packages}/All" \
		&& ls -t | grep '\.t[gb]z$' | while read n; do pkg_info -X "$n"; done) \
		| ${gzip_cmd} > "${packages}"/All/pkg_summary.gz
fi

cat <<EOF > "$upload_general"
#! /bin/sh
set -e
cd "$packages"
rsync $RSFLAGS --files-from="${all_good_packages}" . "$RSYNC_DST/"
EOF
chmod +x "$upload_general"

if [ "$do_upload" = "yes" ]; then
	echo "upload> Uploading packages"
	sh "$upload_general" \
	|| {
		echo "upload> ERROR: rsync failed.  To retry later, you can run $upload_general" 1>&2
		failed=yes
	}
else
	echo "upload> Skipping upload of packages."
	echo "        Run \"$upload_general\" to upload them later."
fi

# clean up temp files
if [ "$failed,$debug,$do_upload" = "no,no,yes" ]; then
	rm -fr "$TMP"
else
	echo "upload> Preserving temporary directory ${TMP}"
fi

if [ "$failed" = "yes" ]; then
	exit 1
fi
