# robotpkg Makefile for:	hardware/fh2805-libs
# Created:			Matthieu Herrb on Mon, 22 Dec 2008
#

DISTNAME=	fh2805-libs-${VERSION}
VERSION=	1.0
CATEGORIES=	hardware
MASTER_SITES=	${MASTER_SITE_OPENROBOTS:=fh2805-libs/}

MAINTAINER=	openrobots@laas.fr
COMMENT=	Driver and interface for Faulhaber 2805 motor controller
LICENSE=	isc

GNU_CONFIGURE=	yes

include ../../devel/mkdep/depend.mk
include ../../pkgtools/libtool/depend.mk
include ../../pkgtools/pkg-config/depend.mk
include ../../mk/robotpkg.mk
