# robotpkg Makefile for:	hardware/mesa-swissranger
# Created:			Jan Paulus on 17 Aug 2010
#

MESA_SWISSRANGER_VERSION=	1.0.14-667
DISTNAME=		libmesasr-dev-${MESA_SWISSRANGER_VERSION}.i386
PKGNAME=		mesa-swissranger-${MESA_SWISSRANGER_VERSION}
CATEGORIES=		hardware
MASTER_SITES=		http://www.mesa-imaging.ch/customer/driver/
#MASTER_REPOSITORY= 	
#http://www.mesa-imaging.ch/customer/driver/libmesasr-dev-1.0.14-667.i386.deb

MAINTAINER=		
HOMEPAGE=		http://www.mesa-imaging.ch
COMMENT=		Mesa SwissRanger driver
LICENSE=		modified-bsd

USE_LANGUAGES=		c c++

GNU_CONFIGURE=		yes


#WRKSRC=			${WRKDIR}/sick-lidar-toolbox-${SICK_LIDAR_TOOLBOX_VERSION}

include ../../mk/robotpkg.mk
