# robotpkg Makefile for:	architecture/genBasic-genom
# Created:			A. degroote on Sat, 17 May 2008
#

DISTNAME=		genBasic-genom-0.3
CATEGORIES=		architecture

MASTER_SITES=		${MASTER_SITE_OPENROBOTS}
MASTER_REPOSITORY=	git ssh://trac.laas.fr/git/robots/genBasic-genom

MAINTAINER=		openrobots@laas.fr
#HOMEPAGE=
COMMENT=		Common simple data structures for GenoM modules

LICENSE=		isc

GNU_CONFIGURE=		yes

GENOM_MODULE=		genBasic
GENOM_ARGS=		-a

include ../../architecture/genom/depend.mk

include ../../mk/robotpkg.mk
