# robotpkg Makefile for:	image/libraw1394
# Created:			Anthony Mallet on Sun, 28 Jan 2007
#

DISTNAME=		libraw1394-2.0.4
CATEGORIES=		image
MASTER_SITES=		${MASTER_SITE_SOURCEFORGE:=libraw1394/}

MAINTAINER=		openrobots@laas.fr
HOMEPAGE=		http://sourceforge.net/projects/libraw1394/
COMMENT=		Provide access to the raw IEEE1394 bus

ONLY_FOR_PLATFORM=	Linux-%

GNU_CONFIGURE=		YES

include ../../mk/robotpkg.mk
