# robotpkg Makefile for:	architecture/robotis-oroyarp
# Created:			Arnaud Degroote on Thu, 22 Apr 2010
#

OROYARP_VERSION=	1.2
DISTNAME=		robotis-oroyarp-${OROYARP_VERSION}
CATEGORIES=		architecture
MASTER_SITES=		http://robotis.onera.fr/sites/robotis.onera.fr/files/
EXTRACT_SUFX=		.tar

MAINTAINER=		openrobots@laas.fr
HOMEPAGE=		http://robotis.onera.fr
COMMENT=		The Orocos / YARP binding
LICENSE=		gnu-lgpl-v3

USE_LANGUAGES=		c c++

include ../../architecture/orocos-ocl/depend.mk
include ../../architecture/orocos-rtt/depend.mk
include ../../architecture/yarp/depend.mk
include ../../mk/sysdep/cmake.mk
include ../../mk/robotpkg.mk
