# robotpkg Makefile for:	mapping/worldmodelgrid3dg-genom
# Created:			Anthony Mallet on Thu, 9 Apr 2009
#

PKGVERSION=	1.0
DISTNAME= 	worldModelGrid3DG-genom-${PKGVERSION}
PKGNAME=	worldmodelgrid3dg-genom-${PKGVERSION}
CATEGORIES=	mapping
MASTER_SITES=	${MASTER_SITE_OPENROBOTS:=worldModelGrid3D-genom/}

MAINTAINER=	openrobots@laas.fr
#HOMEPAGE=	
COMMENT=	Probabilistic, 3D occupancy grid building - GenoM component

GENOM_MODULE=	worldModelGrid3DG

include ../../architecture/genom/depend.mk
include ../../mapping/worldmodelgrid3d/depend.mk
include ../../localization/pom-genom/depend.mk
include ../../math/t3d/depend.mk
include ../../image/stereopixel-genom/depend.mk
include ../../mk/robotpkg.mk
