# robotpkg mathematics
#

COMMENT=	Mathematics

SUBDIR+=	blas
SUBDIR+=	eigen2
SUBDIR+=	fsqp
SUBDIR+=	gbM
SUBDIR+=	gmp
SUBDIR+=	hrp2-dynamics
SUBDIR+=	jrl-dynamics
SUBDIR+=	jrl-mathtools
SUBDIR+=	lapack
SUBDIR+=	mpfr
SUBDIR+=	t3d
SUBDIR+=	tvmet
SUBDIR+=	vnl-vw

include ../mk/robotpkg.subdir.mk
