# robotpkg hardware drivers and low-level software
#

COMMENT=	Hardware drivers and low-level software

SUBDIR+=	GPSNovatel
SUBDIR+=	MTI
SUBDIR+=	contec-pio32-headers
SUBDIR+=	contec-pio32-kmod
SUBDIR+=	cwiid
SUBDIR+=	fh2805-libs
SUBDIR+=	force-genom
SUBDIR+=	gbx-hokuyo-aist
SUBDIR+=	gyroKVH1000
SUBDIR+=	gyroKVH5000
SUBDIR+=	jidogrip-libs
SUBDIR+=	jr3-kmod
SUBDIR+=	libftdi
SUBDIR+=	mouse3d-genom
SUBDIR+=	pa10-kmod
SUBDIR+=	pa10-libs
SUBDIR+=	peak-linux-driver
SUBDIR+=	platine-genom
SUBDIR+=	sahand-kmod
SUBDIR+=	sahand-libs
SUBDIR+=	sahand-genom
SUBDIR+=	serial
SUBDIR+=	sickLib
SUBDIR+=	sick-genom
SUBDIR+=	spnav-kmod
SUBDIR+=	spnav-libs
SUBDIR+=	velodyne-libs

include ../mk/robotpkg.subdir.mk
