# robotpkg localization software
#

COMMENT=	Position estimation and localization

SUBDIR+=	GPS-genom
SUBDIR+=	MTI-genom
SUBDIR+=	imu-genom
SUBDIR+=	gyro-genom
SUBDIR+=	hueblob-genom
SUBDIR+=	insitu
SUBDIR+=	libpom
SUBDIR+=	odokit
SUBDIR+=	pom-genom
SUBDIR+=	segloc-genom

include ../mk/robotpkg.subdir.mk
