# robotpkg Makefile for:	devel/libtool
# Created:			Anthony Mallet on Tue, 15 May 2007
#

DISTNAME=	libtool-2.2.6b
CATEGORIES=	devel pkgtools
MASTER_SITES=	${MASTER_SITE_GNU:=libtool/}

MAINTAINER=	openrobots@laas.fr
HOMEPAGE=	http://www.gnu.org/software/libtool/libtool.html

COMMENT=	Generic shared library support script

GNU_CONFIGURE=	yes

include ../../mk/robotpkg.mk
