# robotpkg Makefile for:	robots/neobotix-libs
# Created:			Matthieu Herrb on Wed, 31 Dec 2008
#


DISTNAME=	neobotix-libs-1.1
CATEGORIES=	robots
MASTER_SITES=	${MASTER_SITE_OPENROBOTS:=neobotix/}

MAINTAINER=	openrobots@laas.fr
COMMENT=	interface library for the neobotix platform

GNU_CONFIGURE=	yes

include ../../hardware/peak-linux-driver/depend.mk
include ../../devel/mkdep/depend.mk
include ../../pkgtools/libtool/depend.mk
include ../../pkgtools/pkg-config/depend.mk
include ../../mk/robotpkg.mk
