# robotpkg Makefile for:	devel/libtorch-laas
# Created:			Brice Burger on Thu, 18 Jun 2009
#

DISTNAME=		torch-3.2
PKGNAME=		libtorch-laas-3.2
CATEGORIES=		devel
MASTER_SITES=		${MASTER_SITE_OPENROBOTS:=libtorch/}
MASTER_REPOSITORY=	git ssh://softs.laas.fr/git/robots/libtorch

MAINTAINER=	openrobots@laas.fr
HOMEPAGE=	http://www.torch.ch/

COMMENT=	Is a machine-learning & computer vision library in simple C++.

GNU_CONFIGURE=		yes
BUILD_TARGET=		all
INSTALL_TARGET=		install

include ../../mk/robotpkg.mk
