# robotpkg Makefile for:	math/eigen2
# Created:			Matthieu Herrb on Wed, 19 May 2010
#
V=		2.0.12
PKGNAME=	eigen2-${V}
DISTNAME=	${V}

CATEGORIES=	math
MASTER_SITES=	http://bitbucket.org/eigen/eigen/get/
WRKSRC=		${WRKDIR}/eigen

MAINTAINER=	openrobots@laas.fr
HOMEPAGE=	http://eigen.tuxfamily.org/
COMMENT=	a C++ template library for linear algebra

USE_LANGUAGES=	c c++

include ../../mk/sysdep/cmake.mk
include ../../mk/robotpkg.mk
