# optimization tools
#

COMMENT=	Optimization tools

SUBDIR+=	ipopt
SUBDIR+=	roboptim-core
SUBDIR+=	roboptim-core-cfsqp-plugin
SUBDIR+=	roboptim-core-ipopt-plugin
SUBDIR+=	roboptim-trajectory

include ../mk/robotpkg.subdir.mk
