# robotpkg Makefile for:	hardware/spnav-kmod
# Created:			Xavier Broquere on Fri, 20 Mar 2009
#


DISTNAME=	spnav-kmod-1.0
CATEGORIES=	hardware
MASTER_SITES=		${MASTER_SITE_OPENROBOTS}

MAINTAINER=	openrobots@laas.fr
HOMEPAGE=	http://spacenav.sourceforge.net/
COMMENT=	Daemon for spacenav 3D mouse
LICENSE=	gnu-gpl-v3

GNU_CONFIGURE=		yes
CONFIGURE_ARGS+=	--disable-x11

include ../../mk/robotpkg.mk
