# robotpkg Makefile for:	math/vnl-vw
# Created:			Anthony Mallet on Fri, 8 Dec 2006
#

include ../../image/vw/Makefile.common

PKGNAME=		vnl-vw-${VW_VERSION}
COMMENT=		Vision Numerics Library of Vision Workbench (VW) Libraries
CATEGORIES=		math devel

# build and install only the VNL library
BUILD_DIRS+=		VNL
INSTALL_DIRS+=		VNL

INSTALLATION_DIRS+=\
	include/VNL/Algo

include ../../mk/robotpkg.mk
