# robotpkg Makefile for:	brics/xerces-c
# Created:			Michael Reckhaus on 07 Oct 2010

XERCES-C_LIBRARY_VERSION=	3.1.1
EXTRACT_SUFX?=		        .tar.gz
DISTNAME=		        xerces-c-${XERCES-C_LIBRARY_VERSION}
PKGNAME=		        xerces-c-${XERCES-C_LIBRARY_VERSION}
CATEGORIES=			parser
MASTER_SITES=        	     	http://ftp.halifax.rwth-aachen.de/apache//xerces/c/3/sources/


MAINTAINER=		  	The Apache Software Foundation
HOMEPAGE=		  	http://ftp.halifax.rwth-aachen.de/apache//xerces/c/3/sources/
COMMENT=		  	Xerces C++ XML Parser library 
LICENSE=		  	apache-2.0

USE_LANGUAGES=			c c++

GNU_CONFIGURE=			yes

include ../../mk/robotpkg.mk

