# robotpkg audio tools
#

COMMENT=	Robotics audio tools

SUBDIR+=	clone-genom
SUBDIR+=	festival
SUBDIR+=	festlex-cmu
SUBDIR+=	festlex-poslex
SUBDIR+=	OGIlexicon
SUBDIR+=	ogi-voice-as-diphone
SUBDIR+=	speett-genom
SUBDIR+=	sphinx2
SUBDIR+=	textos-genom

include ../mk/robotpkg.subdir.mk
