# robotpkg Makefile for:	math/tvmet
# Created:			Anthony Mallet on Thu, 2 Oct 2008
#

DISTNAME=	tvmet-1.7.2
EXTRACT_SUFX=	.tar.bz2

CATEGORIES=	math
MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=tvmet/}

MAINTAINER=	openrobots@laas.fr
HOMEPAGE=	http://tvmet.sourceforge.net/index.html
COMMENT=	Tiny Vector and Matrix Template library.

USE_LANGUAGES+= c c++

GNU_CONFIGURE=	yes

include ../../mk/sysdep/gcc-c++.mk
include ../../mk/robotpkg.mk
