# robotpkg Makefile for:	graphics/laaswm-libs
# Created:			Matthieu Herrb on Mon, 9 Mar 2009
#

DISTNAME=	laaswm-libs-1.0
COMMENT=	Library allowing to control windows in laaswm
CATEGORIES=	graphics

MASTER_SITES=	${MASTER_SITE_OPENROBOTS:=laaswm/}
MASTER_REPOSITORY=	git ssh://trac.laas.fr/git/robots/laaswm-libs

MAINTAINER=	matthieu.herrb@laas.fr

GNU_CONFIGURE=	yes

include ../../mk/sysdep/tcl.mk
include ../../pkgtools/libtool/depend.mk
include ../../mk/robotpkg.mk

