# robotpkg Makefile for:	hardware/jidogrip-libs
# Created:			Matthieu Herrb on Tue, 6 Jan 2009
#

DISTNAME=	jidogrip-libs-1.1
CATEGORIES=	hardware

MASTER_SITES=	${MASTER_SITE_OPENROBOTS:=jido/}

GNU_CONFIGURE=	yes

DEPENDS+=	contec-pio32-headers:../contec-pio32-headers

include ../../hardware/libftdi/depend.mk
include ../../devel/mkdep/depend.mk
include ../../pkgtools/libtool/depend.mk
include ../../pkgtools/pkg-config/depend.mk
include ../../mk/robotpkg.mk
