# robotpkg Makefile for:	robot/rflexclients
# Created:			Arnaud Degroote on Mon, 19 May 2008
#

DISTNAME=		rflexclients-${VERSION}
VERSION=		1.0.1
CATEGORIES=		robot
MASTER_SITES=		${MASTER_SITE_OPENROBOTS}
MASTER_REPOSITORY=\
	cvs cvs.laas.fr:/usr/local/cvs_hilare atrv/rFlex-clients

MAINTAINER=		openrobots@laas.fr
#HOMEPAGE=
COMMENT=		Driver and interface for Rflex

GNU_CONFIGURE=		yes

include ../../pkgtools/libtool/depend.mk
include ../../pkgtools/pkg-config/depend.mk
include ../../devel/mkdep/depend.mk
include ../../mk/robotpkg.mk
