# robotpkg Makefile for:	architecture/genPos-genom
# Created:			Arnaud Degroote on Mon, 19 May 2008
#

DISTNAME=		genPos-genom-0.2

CATEGORIES=		architecture
MASTER_SITES=		${MASTER_SITE_OPENROBOTS}
MASTER_REPOSITORY=	git ssh://trac.laas.fr/git/robots/genPos-genom

MAINTAINER=		openrobots@laas.fr
#HOMEPAGE=
COMMENT=		Common position-related data structures for GenoM

LICENSE=		isc

GNU_CONFIGURE=		yes

GENOM_MODULE=		genPos
GENOM_ARGS=		-a

include ../../architecture/genom/depend.mk

include ../../mk/robotpkg.mk
