# $LAAS: cmake.mk 2009/01/30 12:03:53 mallet $
#
# Copyright (c) 2009 LAAS/CNRS
# All rights reserved.
#
# Permission to use, copy, modify, and distribute this software for any purpose
# with or without   fee is hereby granted, provided   that the above  copyright
# notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS  SOFTWARE INCLUDING ALL  IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR  BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR  ANY DAMAGES WHATSOEVER RESULTING  FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION,   ARISING OUT OF OR IN    CONNECTION WITH THE USE   OR
# PERFORMANCE OF THIS SOFTWARE.
#
#                                             Anthony Mallet on Thu Jan 22 2009
#

DEPEND_DEPTH:=		${DEPEND_DEPTH}+
CMAKE_DEPEND_MK:=	${CMAKE_DEPEND_MK}+

ifeq (+,$(DEPEND_DEPTH))
DEPEND_PKG+=		cmake
endif

ifeq (+,$(CMAKE_DEPEND_MK)) # ----------------------------------------------

PREFER.cmake?=		system

DEPEND_USE+=		cmake
DEPEND_ABI.cmake?=	cmake>=2.6
DEPEND_METHOD.cmake+=	build
SYSTEM_SEARCH.cmake=	'bin/cmake:s/[^-.0-9]//g;y/-/./;p:% --version'

USE_CMAKE=		yes
export CMAKE=		${PREFIX.cmake}/bin/cmake


# Use the install_manifest.txt file generated by cmake install for the
# print-PLIST target, because cmake doesn't change the date of installed
# files.
#
PRINT_PLIST_FILES_CMD+=\
	${CAT} $(addsuffix /install_manifest.txt,${BUILD_DIRS}) 2>/dev/null;


endif # CMAKE_DEPEND_MK ----------------------------------------------------

DEPEND_DEPTH:=		${DEPEND_DEPTH:+=}
