# $Id: Makefile 2010/07/08 23:08:58 tho $
#

BROKEN=			Distfile disappeared

DISTNAME=		festvox_cmu_us_awb_arctic_hts
PKGNAME=		festvox-cmu-us-awb-arctic-hts-20041209
CATEGORIES=		audio
MASTER_SITES=		http://festvox.org/packed/festival/latest/

MAINTAINER=		openrobots@laas.fr
HOMEPAGE=		http://festvox.org/index.html
COMMENT=		CMU ARCTIC voice by AWB

WRKSRC=			${WRKDIR}/festival
NO_BUILD=		yes

include ../../audio/festival/depend.mk
include ../../audio/festlex-cmu/depend.mk
include ../../audio/festlex-poslex/depend.mk
include ../../pkgtools/pax/depend.mk
include ../../mk/robotpkg.mk

do-install:
	${INSTALL_DATA_DIR} ${PREFIX}/share/festival
	cd ${WRKSRC} && ${PAX} -rw . ${PREFIX}/share/festival/.
