# robotpkg Makefile for:	brics/rudeconfig
# Created:			Jan Paulus on 12 Nov 2010

RUDECONFIG_VERSION=	5.0.5
DISTNAME=		          rudeconfig-${RUDECONFIG_VERSION}
PKGNAME=		          rudeconfig-${RUDECONFIG_VERSION}
CATEGORIES=		        hardware
MASTER_SITES=         http://rudeserver.com/config/download/


MAINTAINER=		Rick Wagner
HOMEPAGE=		  http://rudeserver.com/config/api.html
COMMENT=		  RudeConfig Open Source C++ Config File Library
LICENSE=		  gnu-gpl-v2

USE_LANGUAGES=		c c++

GNU_CONFIGURE=		yes


include ../../mk/robotpkg.mk

