# robotpkg Makefile for:	mapping/libdtm
# Created:			Arnaud Degroote on Thu, 6 Aug 2009
#

DISTNAME=		libdtm-1.1
CATEGORIES=		mapping
MASTER_SITES=		${MASTER_SITE_OPENROBOTS}
MASTER_REPOSITORY=	git ssh://softs.laas.fr/git/robots/libdtm


MAINTAINER=		openrobots@laas.fr
#HOMEPAGE=
COMMENT=		Digital Terrain Modeling lib

GNU_CONFIGURE=		yes

include ../../graphics/gdhe/depend.mk
include ../../image/libimages3d/depend.mk
include ../../math/t3d/depend.mk
include ../../pkgtools/pkg-config/depend.mk
include ../../mk/robotpkg.mk
