# robotpkg Makefile for:	hardware/spnav-libs
# Created:			Xavier Broquere on Fri, 20 Mar 2009
#


DISTNAME=	spnav-libs-1.0
CATEGORIES=	hardware
MASTER_SITES=		${MASTER_SITE_OPENROBOTS}

MAINTAINER=	openrobots@laas.fr
HOMEPAGE=	http://spacenav.sourceforge.net/
COMMENT=	Library for spacenav 3D mouse
LICENSE=	modified-bsd

GNU_CONFIGURE=		yes

include ../../mk/robotpkg.mk
