# robotpkg Makefile for:	mapping/mapkit
# Created:			Anthony Mallet on Tue, 17 Jun 2008
#

DISTNAME=		mapkit-1.0
CATEGORIES=		mapping
MASTER_SITES=		${MASTER_SITE_OPENROBOTS}

MAINTAINER=		openrobots@laas.fr
#HOMEPAGE=
COMMENT=		2D, segment-based map building tools

GNU_CONFIGURE=		yes

DEPENDS+=		mkdep>=2.6:../../devel/mkdep

include ../../devel/pocolibs/depend.mk
include ../../pkgtools/libtool/depend.mk
include ../../pkgtools/pkg-config/depend.mk
include ../../localization/odokit/depend.mk
include ../../mapping/segkit/depend.mk
include ../../mk/robotpkg.mk
