# robotpkg Makefile for:	image/libimages3d
# Created:			Anthony Mallet on Wed, 5 Dec 2007
#

DISTNAME=		libimages3d-3.3
CATEGORIES=		image
MASTER_SITES=		${MASTER_SITE_OPENROBOTS:=libimages3d/}

MAINTAINER=		openrobots@laas.fr
#HOMEPAGE=
COMMENT=		Three dimensional image definition
LICENSE=		2-clause-bsd

GNU_CONFIGURE=		yes

include ../../math/t3d/depend.mk
include ../../pkgtools/pkg-config/depend.mk
include ../../mk/robotpkg.mk
