# robotpkg Makefile for:	hardware/MTI
# Created:			Arnaud Degroote on Thu, 17 Jul 2008
#

DISTNAME=		MTI-${VERSION}
VERSION=		0.4
CATEGORIES=		hardware
MASTER_SITES=		${MASTER_SITE_OPENROBOTS}
MASTER_REPOSITORY=	git ssh://softs.laas.fr/git/robots/MTI-libs

MAINTAINER=		openrobots@laas.fr
#HOMEPAGE=
COMMENT=		Driver and interface for MTI

USE_LANGUAGES+=         c c++
GNU_CONFIGURE=		yes

include ../../devel/mkdep/depend.mk
include ../../pkgtools/libtool/depend.mk
include ../../pkgtools/pkg-config/depend.mk
include ../../mk/robotpkg.mk
