# robotpkg Makefile for:	scripts/purple-ball
# Created:			Anthony Mallet on Wed, 24 Mar 2010
#

DISTNAME=		purple-ball-1.1

CATEGORIES=		scripts
MASTER_SITES=		${MASTER_SITE_OPENROBOTS:=purple-ball/}
MASTER_REPOSITORY=	git ssh://softs.laas.fr/git/robots/purple-ball

MAINTAINER=	mallet@laas.fr
COMMENT=	Supervision scripts for the HRP-2 "purple-ball" demonstration
LICENSE=	2-clause-bsd

USE_LANGUAGES=	# empty

GNU_CONFIGURE=	yes

include ../../robots/hrp2-genom/depend.mk
include ../../audio/speett-genom/depend.mk
include ../../audio/textos-genom/depend.mk
include ../../image/viam-genom/depend.mk
include ../../image/stereopixel-genom/depend.mk
include ../../localization/hueblob-genom/depend.mk
include ../../path/gik-genom/depend.mk
include ../../motion/mwalk-genom/depend.mk
include ../../shell/eltclsh/depend.mk
include ../../mk/sysdep/tcl.mk
include ../../mk/sysdep/tk.mk
include ../../mk/robotpkg.mk
