# robotpkg Makefile for:	graphics/laaswm
# Created:			Matthieu Herrb on Mon, 9 Mar 2009
#

DISTNAME=	laaswm-1.0
COMMENT=	Remotely controllable window manager based on evilwm
CATEGORIES=	graphics

MASTER_SITES=	${MASTER_SITE_OPENROBOTS:=laaswm/}
MASTER_REPOSITORY=	git ssh://trac.laas.fr/git/robots/laaswm

MAINTAINER=	matthieu.herrb@laas.fr

GNU_CONFIGURE=	yes

include ../../pkgtools/libtool/depend.mk
include ../../mk/robotpkg.mk

