# robotpkg Makefile for:	hardware/platine-genom
# Created:			Anthony Mallet on Tue, 17 Jun 2008
#

DISTNAME=		platine-genom-0.1
CATEGORIES=		hardware
MASTER_SITES=		${MASTER_SITE_OPENROBOTS}
MASTER_REPOSITORY=	git softs.laas.fr:/git/robots/platine-genom

MAINTAINER=		openrobots@laas.fr
#HOMEPAGE=
COMMENT=		GenoM module for platine management.

GNU_CONFIGURE=		yes

GENOM_MODULE=		platine
include ../../architecture/genom/depend.mk

include ../../architecture/genBasic-genom/depend.mk
include ../../localization/pom-genom/depend.mk
include ../../mk/robotpkg.mk
