# robotpkg Makefile for:	devel/gbx-share
# Created:			Anthony Mallet on Wed, 17 Mar 2010
#
GBX_PACKAGE=	share-${GBX_VERSION}
GBX_COMMENT=	(shared files)

CATEGORIES=	devel
include ../../meta-pkgs/gearbox/Makefile.common

CMAKE_ARGS+=	-DGBX_INSTALL_CMAKE_SCRIPTS=ON

include ../../mk/robotpkg.mk
