# robotpkg Makefile for:	manipulation/xarm-genom
# Created:			Anthony Mallet on Tue, 28 Jul 2009
#

DISTNAME=	xarm-genom-1.0
CATEGORIES=	manipulation
MASTER_SITES=	${MASTER_SITE_OPENROBOTS:=xarm/}

MAINTAINER=	xbroquer@laas.fr
#HOMEPAGE=	softs.laas.fr:/ftp/pub/openrobots/
COMMENT=	Controls a 6DOF arm in cartesian space.

GNU_CONFIGURE=	yes

GENOM_MODULE=	xarm
include ../../architecture/genom/depend.mk
include ../../hardware/mouse3d-genom/depend.mk
include ../../localization/pom-genom/depend.mk
include ../../math/gbM/depend.mk
include ../../pkgtools/pkg-config/depend.mk
include ../../robots/qarm-genom/depend.mk
include ../../mk/robotpkg.mk
