# robotpkg programming languages
#

COMMENT=	Programming languages

SUBDIR+=	gcc42-c
SUBDIR+=	gcc42-c++
SUBDIR+=	gcc42-fortran
SUBDIR+=	jython
SUBDIR+=	python3
SUBDIR+=	sun-jdk14
SUBDIR+=	sun-jdk6
SUBDIR+=	sun-jre14
SUBDIR+=	sun-jre6

include ../mk/robotpkg.subdir.mk
