# robotpkg Makefile for:	localization/odokit
# Created:			Anthony Mallet on Tue, 17 Jun 2008
#

DISTNAME=		odokit-1.0
CATEGORIES=		localization
MASTER_SITES=		${MASTER_SITE_OPENROBOTS}

MAINTAINER=		openrobots@laas.fr
#HOMEPAGE=
COMMENT=		Library to manipulate odometry data

GNU_CONFIGURE=		yes

DEPENDS+=		mkdep>=2.6:../../devel/mkdep

include ../../pkgtools/libtool/depend.mk
include ../../pkgtools/pkg-config/depend.mk
include ../../mapping/segkit/depend.mk
include ../../mk/robotpkg.mk
