# robotpkg robots specific packages
#

COMMENT=	Robots specific packages

SUBDIR+=	fingers-genom
SUBDIR+=	hrp2-14
SUBDIR+=	hrp2-builder
SUBDIR+=	hrp2-genom
SUBDIR+=	hrpsys-jrl
SUBDIR+=	jloco-genom
SUBDIR+=	neobotix-libs
SUBDIR+=	play-genom
SUBDIR+=	player20-libs
SUBDIR+=	qarm-genom
SUBDIR+=	rflex-genom
SUBDIR+=	rflexclients
SUBDIR+=	rmp400-genom
SUBDIR+=	rmp-libs
SUBDIR+=	scout-genom

include ../mk/robotpkg.subdir.mk
