# robotpkg Makefile for:	hardware/force-genom
# Created:			Nizar Khalifa Sallem on Tue, 28 Jul 2009
#

DISTNAME=		force-genom-1.1.1
CATEGORIES=		hardware
MASTER_SITES=		${MASTER_SITE_OPENROBOTS:=force-genom/}
MASTER_REPOSITORY=	git ssh://trac.laas.fr/git/robots/force-genom


MAINTAINER=		daniel@laas.fr
#HOMEPAGE=
COMMENT=		GenoM module for the JR3 90M31A force sensor management.

GNU_CONFIGURE=		yes

GENOM_MODULE=		force

include ../../architecture/genom/depend.mk
include ../../math/gbM/depend.mk
include ../../mk/robotpkg.mk
