# robotpkg Makefile for:	image/sift
# Created:			nksallem on Wed, 9 Jun 2010
#

PKGVERSION=		1.1.2
DISTNAME=		sift-${PKGVERSION}_20100521
PKGNAME=		sift-${PKGVERSION}
CATEGORIES=		image
MASTER_SITES=		http://web.engr.oregonstate.edu/~hess/downloads/sift/

MAINTAINER=		openrobots@laas.fr
HOMEPAGE=		http://web.engr.oregonstate.edu/~hess
COMMENT=		GPL v2 implementation of David Lowe SIFT

WRKSRC=			${WRKDIR}/sift

USE_LANGUAGES+=		c c++
USE_PKGLOCALEDIR=	yes

NO_CONFIGURE=           yes

include ../../image/opencv/depend.mk
include ../../mk/sysdep/gtk.mk
include ../../pkgtools/libtool/depend.mk
include ../../pkgtools/pkg-config/depend.mk
include ../../mk/robotpkg.mk
