# robotpkg abstract programming interfaces
#

COMMENT=	Abstract programming interfaces

SUBDIR+=	jrl-interface-dynamics
SUBDIR+=	jrl-interface-giktask
SUBDIR+=	jrl-mal

include ../mk/robotpkg.subdir.mk
