# robotpkg Makefile for:	robots/scout-genom
# Created:			Matthieu Herrb on Mon, 14 Dec 2009
#

DISTNAME=		scout-genom-0.1
CATEGORIES=		robots
MASTER_SITES=		${MASTER_SITE_OPENROBOTS:=scout/}

MAINTAINER=		openrobots@laas.fr

COMMENT=		GenoM module for Nomadic SuperScouts management.

GNU_CONFIGURE=		yes


GENOM_MODULE=		scout

include ../../architecture/genom/depend.mk
include ../../mk/robotpkg.mk
