# robotpkg Makefile for:	lang/sun-jre6
# Created:			Anthony Mallet on Fri, 3 Oct 2008
#

DISTNAME=	jre-6u7-linux-i586
PKGNAME=	sun-jre6-6.0.7
MASTER_SITES=	# empty

DOWNLOAD_NAME=	Java Runtime Environment (JRE) 6u7
SHORT_NAME=	JRE

WRKSRC=		${WRKDIR}/jre1.6.0_07
JAVA_WRAPPERS=	java javaws keytool orbd policytool rmid rmiregistry \
		servertool tnameserv

LICENSE=	sun-jre6-license

include ../../lang/sun-jre6/Makefile.common
include ../../mk/robotpkg.mk

