# robotpkg Makefile for:	hardware/pa10-libs
# Created:			Matthieu Herrb on Mon, 22 Dec 2008
#

DISTNAME=	pa10-libs-${VERSION}
VERSION=	1.1.2
CATEGORIES=	hardware
MASTER_SITES=	${MASTER_SITE_OPENROBOTS}

MAINTAINER=	openrobots@laas.fr
COMMENT=	libraries for Mitsubishi PA10 Arm controller

GNU_CONFIGURE=	yes

include ../../pkgtools/libtool/depend.mk
include ../../pkgtools/pkg-config/depend.mk
include ../../mk/robotpkg.mk
