# robotpkg Makefile for:	brics/hokuyo_urg_library
# Created:			Michael Reckhaus on 24 Aug 2010

BOOST_LOG_VERSION=	1.0
EXTRACT_SUFX?=		.zip
DISTNAME=		boost-log-${BOOST_LOG_VERSION}
PKGNAME=		boost-log-${BOOST_LOG_VERSION}
CATEGORIES=		system
MASTER_SITES= 		http://downloads.sourceforge.net/project/boost-log/

#MAINTAINER=		
#HOMEPAGE=		
COMMENT=		Boost Log
#LICENSE=		gnu-lgpl-v3

USE_LANGUAGES=		c c++

#GNU_CONFIGURE=		yes





include ../../mk/robotpkg.mk

