# robotpkg Makefile for:	pkgtools/pkg-config
# Created:			Anthony Mallet on Wed, 19 Mar 2008
#

DISTNAME=		pkg-config-0.23
CATEGORIES=		pkgtools
MASTER_SITES=		http://pkgconfig.freedesktop.org/releases/

MAINTAINER=		openrobots@laas.fr
HOMEPAGE=		http://pkgconfig.freedesktop.org/
COMMENT=		System for managing library compile/link flags

GNU_CONFIGURE=		yes

CONFIGURE_ARGS+=	--disable-threads

include ../../pkgtools/libtool/depend.mk
include ../../mk/robotpkg.mk
