# robotpkg Makefile for:	robots/fingers-genom
# Created:			Matthieu Herrb on Mon, 12 Jan 2009
#

DISTNAME=	fingers-genom-1.0
CATEGORIES=	robots
COMMENT=	Jido fingers control module - Genom componenent
MASTER_SITES=	${MASTER_SITE_OPENROBOTS:=jido/}

GNU_CONFIGURE=	yes

GENOM_MODULE=	fingers

include ../../hardware/jidogrip-libs/depend.mk
include ../../devel/mkdep/depend.mk
include ../../architecture/genom/depend.mk
include ../../localization/pom-genom/depend.mk
include ../../architecture/genPos-genom/depend.mk
include ../../mk/robotpkg.mk


