# robotpkg Makefile for:	brics/soqt
# Created:			Michael Reckhaus on 07 Oct 2010

SOQT_LIBRARY_VERSION=	1.5.0
DISTNAME=		        SoQt-${SOQT_LIBRARY_VERSION}
PKGNAME=		        SoQt-${SOQT_LIBRARY_VERSION}
CATEGORIES=			graphics
MASTER_SITES=        	     	http://ftp.coin3d.org/coin/src/all/


MAINTAINER=		  	The Apache Software Foundation
HOMEPAGE=		  	http://ftp.coin3d.org/coin/src/all/
COMMENT=		  	SoQt the bridge between 2d Qt and Coin 3d
LICENSE=		  	gnu-gpl-v2

USE_LANGUAGES=			c c++

GNU_CONFIGURE=			yes

include ../qt/depend.mk
include ../coin3d/depend.mk
include ../../mk/robotpkg.mk

