# $LAAS: Makefile 2008/07/15 13:58:35 mallet $
#
# Copyright (c) 2008 LAAS/CNRS
# All rights reserved.
#
# Redistribution and use  in source  and binary  forms,  with or without
# modification, are permitted provided that the following conditions are
# met:
#
#   1. Redistributions of  source  code must retain the  above copyright
#      notice and this list of conditions.
#   2. Redistributions in binary form must reproduce the above copyright
#      notice and  this list of  conditions in the  documentation and/or
#      other materials provided with the distribution.
#
#                                      Anthony Mallet on Tue Jul 15 2008
#

COMMENT=        Networking tools

SUBDIR+=        evart-client
SUBDIR+=        evart-stream
SUBDIR+=	tclpcap

include ../mk/robotpkg.subdir.mk
