# robotpkg Makefile for:	devel/libedit
# Created:			Anthony Mallet on Tue, 13 Mar 2007
#

DISTNAME=		libedit-20090111-3.0
PKGNAME=		libedit-3.0
CATEGORIES=		devel
MASTER_SITES=		http://www.thrysoee.dk/editline/

MAINTAINER=		openrobots@laas.fr
HOMEPAGE=		http://www.thrysoee.dk/editline/
COMMENT=		Generic line editing and history functions.

LICENSE=		modified-bsd

NOT_FOR_PLATFORM=	# empty

GNU_CONFIGURE=		yes

include ../../mk/sysdep/termcap.mk
include ../../mk/robotpkg.mk
